version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    env_file:
      - ./Backend/.env
    volumes:
      - ./Backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: unless-stopped
